### ISSUE TITLE
App crash when add react-native-facerecognition

### ISSUE THREAD

**Issue by trananh2001** [assemmohamedali/react-native-facerecognition#12]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. HTC]
 - OS: [e.g. Android]

**Additional context**

**Comment by assemmohamedali** [comment]
Please desctibe your problem

**Comment by assemmohamedali** [comment]
Please describe your problem

**Comment by shubhammehta78** [comment]
I am also facing the same problem!!!
