### ISSUE TITLE
React Native warn me using this package

### ISSUE THREAD

**Issue by n-nitchevski** [assemmohamedali/react-native-facerecognition#16]
Here's the log I got when trying to install this package.
I hope you to follow their guide to make it better.
Thanks.

The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-facerecognition: https://github.com/assemmohamedali/react-native-facerecognition#readme
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.

**Comment by aboozaid** [comment]
Thank you
