### ISSUE TITLE
I am building app using this library but its showing me error error: package com.reactnative.facerecognition does not exist

### ISSUE THREAD

**Issue by fahadsolangi** [assemmohamedali/react-native-facerecognition#17]
C:\Users\Fahad-Security\Desktop\RNCamera\example\node_modules\react-native-facerecognition\android\app\src\main\java\opencv\android\FaceCameraManage.java:
uses or overrides a deprecated API.
Recompile with -Xlint:deprecation for details. 
error: package com.reactnative.facerecognition does not exist

**Comment by aboozaid** [comment]
you need to link the library before using it!
