### ISSUE TITLE
Getting the error: null is not an object (evaluating 'CameraManager.Aspect') 

### ISSUE THREAD

**Issue by MadhavBahl** [assemmohamedali/react-native-facerecognition#18]
Hey, I am getting the above-mentioned error while running your example code,, can you help?

**Comment by aboozaid** [comment]
Did you put camera permissions?

**Comment by MadhavBahl** [comment]
Exactly, that resolved the issue.
Thanks!

**Comment by chetanbhadarka** [comment]
> Did you put camera permissions?

Where to put permission and how can i do this, can you please explain me step by step.

Thanks.
