### ISSUE TITLE
Can not found symbol error

### ISSUE THREAD

**Issue by shubhammehta78** [assemmohamedali/react-native-facerecognition#19]
/home/shubham/Desktop/projects/FaceRecognition/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:18: error: cannot find symbol
import cv.reactnative.FaceModulePackage;
                     ^
  symbol:   class FaceModulePackage
  location: package cv.reactnative
/home/shubham/Desktop/projects/FaceRecognition/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:64: error: cannot find symbol
      new FaceModulePackage()
          ^
  symbol:   class FaceModulePackage
  location: class PackageList
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by alastudio** [comment]
Change: import cv.reactnative.FaceModulePackage;
To: import cv.reactnative.facerecognition.FaceModulePackage;

File location: MyApplication.java

**Comment by phuc98ute** [comment]
> Change: import cv.reactnative.FaceModulePackage;
> To: import cv.reactnative.facerecognition.FaceModulePackage;
> 
> File location: MyApplication.java

What file must be changed? Error in build\generated\rncli\src\main\java\com\facebook\react\PackageList.java. But PackageList.java auto generated when rebuild project.
Thanks

**Comment by alastudio** [comment]
File located at your main java file. Root
project/android/app/src/main/java/com/[your app]

**Comment by aboozaid** [comment]
if the issue still exists feel free to re-open.

**Comment by Abhishek150190** [comment]
Yes changed the file but still same issue exists
