### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Angelk90** [assemmohamedali/react-native-facerecognition#2]
Hi @assemmohamedali, 
It would be possible to implement the following features:
1) face detection: https://technode.com/wp-content/uploads/2014/11/Face++.png
2) face filter: https://imgix.bustle.com/uploads/image/2017/6/15/f9ce3a73-c080-4071-a9fc-8df0cf99da48-road-trip-sleep-mask.png

**Comment by assemmohamedali** [comment]
We'll consider all the features in our progress way.
Thanks. I'll close the Issue for now
