### ISSUE TITLE
Error while updating property 'mounted' of a view managed of :FaceCamera

### ISSUE THREAD

**Issue by zhuzhuojiang** [assemmohamedali/react-native-facerecognition#24]
Got two errors with your example while start it:

1.
------
Error while updating property 'mounted' of a view managed of :FaceCamera

null

No implementation found for long org.opencv.face.LBPHFaceRecognizer.created_0(int,int,int,int,double) (tried Java_org_opencv_face_LBPHFaceRecognizer_create_10 and Java_org_opencv_face_LBPHFaceRecognizer_create_10__IIID)

updateViewProp
ViewManagersPropertyCache.java: 95

------

2.  Package not found - OpenCV Manager package was not found! Try to install it? 

Any suggestion, Thanks

**Comment by zhuzhuojiang** [comment]
important to add the jnilibs, resovled

**Comment by Sam1141968878** [comment]
How did you fix it? I showed up

**Comment by Sam1141968878** [comment]
Is there any update？
