### ISSUE TITLE
The package is outdated and not working more ! 

### ISSUE THREAD

**Issue by joy-mollick** [assemmohamedali/react-native-facerecognition#58]
Could not determine the dependencies of task ':app:preDebugBuild' 
Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'
Could not resolve project :react-native-facerecognition ,
......
.....
.....
etc. 

plz update the package or close this .

**Comment by aboozaid** [comment]
It's been a while since I updated the package core and I hope sooner to re-commit to the package again! Sorry

**Comment by joy-mollick** [comment]
I am awaiting for that . plz update soon .....
