### ISSUE TITLE
ASK: Where do you save the dataset?

### ISSUE THREAD

**Issue by rayj10** [assemmohamedali/react-native-facerecognition#7]
**Is your feature request related to a problem? Please describe.**
First of all, thanks for the amazing possibilities you opened by making this library.
My only question after reading your documentation is regarding the dataset itself.
I get a feeling that this is managed by you or your library currently using either your server or phone's storage.
Please correct me if my assumption was wrong :)
If I want to integrate my app with this feature to existing database, how would I go about it?

**Describe the solution you'd like**
It would be amazing if we can supply the dataset too to your library so that we could have integrated system/database for say a Guest Book app across multiple branches of the same company.
Please let me know! :)

Thanks again!

**Comment by assemmohamedali** [comment]
The library handles a dataset behind the scene and improves its quality as much as possible. for example if you're looking for a book app what you need is to train people faces into the camera while the library in background handles these photos and saved them into SharedPreferences so after that when you call recognize function it will identify who this person and callback its name & confidence (you can use this name to make something in your database or logic).

But currently, there is no way to add your dataset directly to be trained. I will remark this issue as new feature. Thanks

**Comment by rayj10** [comment]
Amazing! thanks for the quick response :)

**Comment by zayasa** [comment]
Thanks for your usefull lib, is imposible for me to get training images and display all of it to make sure our user if theirs image

**Comment by assemmohamedali** [comment]
Check out the last version, I have added this
